### ISSUE TITLE
Sterilization of the Human race on top floor of house.

### ISSUE THREAD

**Issue by streed** [714warren/network#2]
Please fix.

**Comment by ianweller** [comment]
I've got bad news about the wifi then

**Comment by ianweller** [comment]
Closing as the current storm should resolve this, reopen if it doesn't

**Comment by streed** [comment]
I didn't die.

**Comment by streed** [comment]
After months of freedom, the scourge of the unmentionables except by grouping @714warren/people-in-reed-s-room-that-shouldn-t-be have not been properly dealt with. Will update issue when back in town.

**Comment by ilianaw** [comment]
what?
